remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: Emily Lister
logo: docs/assets/headshot.png
description: Aerospace Administration major and Computer Science minor student hoping to pursue a Computer Science Masters and focused on systems programming, data structures, and computer architecture. Passionate about precision, scalability, and aviation technology.
